refactor: adjust architecture hexagonal
evilfeeh/self-attendence-totem pull request #19
Opened 2024-05-07 04:17 UTC by marceloribeirosilva

2024-05-07 11:30 UTC, barreto0 requested changes
Perfeita organização, faz mais sentido ser estruturado dessa maneira a desacoplar a entidade do dominio. 
Precisa apenas arrumar os imports que estão quebrados.

2024-05-07 13:11 UTC, barreto0 commented on src/Tests/Application/Entities/Customer.test.ts
> -
testes removidos para serem implementados no teste do Customer Service

2024-05-07 13:11 UTC, barreto0 approved these changes

2024-05-08 01:15 UTC, devtomasjr approved these changes

2024-05-08 02:04 UTC, evilfeeh approved these changes

2024-05-08 02:04 UTC, merged